---
- hosts: all
- name: Include dynamic variables
  ansible.builtin.import_playbook: ../static-assignments/update.yaml

- hosts: db
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/db.yaml

- hosts: nginx
- name: nginx assignment
  ansible.builtin.import_playbook: ../static-assignments/lb.yaml

- hosts: artifactory
- name: artifactory assignment
  ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

#- hosts: sonar
#- name: sonar assignment
#  ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml
